name: cache

on:
  workflow_dispatch:

jobs:
  test-cache:
    name: job to test the cache
    runs-on: ubuntu-latest
    steps:
      - name: checkout the main branch for requirements file
        uses: actions/checkout@v5.0.0
      - name: generate cache
        id: generateCache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: confirm cache
        if: steps.generateCache.outputs.cache-hit == 'true'
        run: echo Cache entry found
          
    
